apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  volumes:
  - name: myvolume
    emptyDir: {}
  containers:
  - name: volume-demo
    image: "busybox"
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    env:
      - name: ENV-FROM-CONFIG
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: key1